"""Generate Claude Code subagent definitions from Pluto role files.

``.claude/agents/pluto-<role>.md`` packages a worker-shaped Pluto role
(specialist, reviewer, qa) as a native Claude Code subagent: the parent
session can delegate with "use the pluto-reviewer subagent to review X"
and the subagent arrives already carrying the role, the protocol digest,
and the shared-identity conventions for inherited MCP servers.

The checked-in files are generated by this module so they cannot drift
from ``library/roles/*.md`` — a test regenerates and compares them.

Usage:
    python -m agent_mcp_friend.subagents --out .claude/agents \
        --roles specialist reviewer qa
    # --own-identity emits an inline mcpServers block that spawns a
    # dedicated PlutoMCPFriend (own agent_id, own inbox). It embeds
    # machine-specific paths — generate locally, never check in.
"""

from __future__ import annotations

import argparse
import os
import sys

from agent_mcp_friend.prompts import (
    default_protocol_digest_path,
    default_roles_dir,
    project_path,
)

# Tool grants per role, mirroring each role file's Hard Constraints:
# the reviewer may make trivial locked edits but not create files; QA
# runs tests but does not edit.
_ROLE_TOOLS = {
    "specialist": "Read, Glob, Grep, Edit, Write, Bash, mcp__pluto",
    "reviewer": "Read, Glob, Grep, Edit, Bash, mcp__pluto",
    "qa": "Read, Glob, Grep, Bash, mcp__pluto",
}
_DEFAULT_TOOLS = "Read, Glob, Grep, Bash, mcp__pluto"

_ROLE_DESCRIPTIONS = {
    "specialist": (
        "Pluto-coordinated code specialist. Use to implement an assigned "
        "code change under Pluto locks and report a task_result back over "
        "Pluto."
    ),
    "reviewer": (
        "Pluto-coordinated reviewer. Use to review a diff or task output "
        "against its definition_of_done and produce a protocol `review` "
        "verdict."
    ),
    "qa": (
        "Pluto-coordinated QA runner. Use to execute the test suite for "
        "completed tasks and produce a protocol `qa_result`."
    ),
}

_PROTOCOL_LINE = (
    "You MUST follow the shared protocol at `library/protocol.md`."
)
_PROTOCOL_SUBSTITUTE = (
    "You MUST follow the shared Pluto protocol. A digest is inlined at "
    "the end of this prompt; the full text is available as the MCP "
    "resource `pluto://protocol` — fetch it when you need exact message "
    "schemas. Do NOT read protocol.md from disk."
)

_SUBAGENT_CONVENTIONS = """\
## Subagent conventions (inherited Pluto MCP server)

You run as a Claude Code subagent and share the PARENT session's Pluto
identity and inbox:

- NEVER call `pluto_recv` or `pluto_pop` — draining would steal the
  parent's messages. Use `pluto_inbox_watch(drain=false)` for a
  non-consuming snapshot if you must observe the inbox.
- Outbound `pluto_send` / `pluto_task_update` go out under the parent's
  `agent_id`; mention your role inside the payload only where the
  protocol schema calls for it.
- Return your work product (the `review` / `qa_result` / `task_result`
  JSON) as your final message to the parent — the parent owns delivery
  and inbox handling.
"""


def build_subagent_md(
    role_name: str,
    *,
    roles_dir: str | None = None,
    own_identity: bool = False,
    python_bin: str | None = None,
    host: str = "127.0.0.1",
    http_port: int = 9201,
) -> str:
    """Render the full ``pluto-<role>.md`` subagent definition."""
    roles = roles_dir or default_roles_dir()
    role_path = os.path.join(roles, f"{role_name}.md")
    with open(role_path, encoding="utf-8") as f:
        role_content = f.read().strip()

    role_content = role_content.replace(_PROTOCOL_LINE, _PROTOCOL_SUBSTITUTE)

    with open(default_protocol_digest_path(), encoding="utf-8") as f:
        digest = f.read().strip()

    frontmatter = [
        "---",
        f"name: pluto-{role_name}",
        "description: " + _ROLE_DESCRIPTIONS.get(
            role_name,
            f"Pluto-coordinated {role_name}. Use for {role_name} work in a "
            f"Pluto team.",
        ),
        f"tools: {_ROLE_TOOLS.get(role_name, _DEFAULT_TOOLS)}",
    ]
    if own_identity:
        py = python_bin or sys.executable
        entry = project_path("src_py", "agent_mcp_friend", "pluto_mcp_friend.py")
        frontmatter += [
            "mcpServers:",
            "  pluto:",
            f"    command: {py}",
            "    args:",
            f"      - {entry}",
            "      - --agent-id",
            f"      - pluto-{role_name}-sub",
            "      - --host",
            f"      - {host}",
            "      - --http-port",
            f"      - {http_port}",
        ]
    frontmatter.append("---")

    conventions = "" if own_identity else "\n" + _SUBAGENT_CONVENTIONS
    return (
        "\n".join(frontmatter)
        + "\n\n"
        + role_content
        + "\n\n---\n"
        + conventions
        + "\n---\n\n"
        + digest
        + "\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate .claude/agents/pluto-<role>.md files",
    )
    parser.add_argument("--out", default=project_path(".claude", "agents"))
    parser.add_argument(
        "--roles", nargs="+", default=["specialist", "reviewer", "qa"],
    )
    parser.add_argument("--roles-dir", default=None)
    parser.add_argument(
        "--own-identity", action="store_true",
        help="emit an inline mcpServers block with a dedicated agent_id "
             "(machine-specific paths — do not check in)",
    )
    parser.add_argument("--python-bin", default=None)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--http-port", type=int, default=9201)
    parser.add_argument(
        "--check", action="store_true",
        help="compare against existing files instead of writing; exit 1 "
             "on drift",
    )
    args = parser.parse_args(argv)

    os.makedirs(args.out, exist_ok=True)
    drift = False
    for role in args.roles:
        rendered = build_subagent_md(
            role,
            roles_dir=args.roles_dir,
            own_identity=args.own_identity,
            python_bin=args.python_bin,
            host=args.host,
            http_port=args.http_port,
        )
        target = os.path.join(args.out, f"pluto-{role}.md")
        if args.check:
            try:
                with open(target, encoding="utf-8") as f:
                    current = f.read()
            except OSError:
                current = None
            if current != rendered:
                print(f"DRIFT: {target}", file=sys.stderr)
                drift = True
            continue
        with open(target, "w", encoding="utf-8") as f:
            f.write(rendered)
        print(target)
    return 1 if drift else 0


if __name__ == "__main__":
    raise SystemExit(main())
